// Pêche TCF vocabulary bank
// Curated starter bank organised by CEFR level + practical TCF themes.
// Fields: level, theme, French, Chinese.
// This is an original study list for Pêche; it is not an official TCF vocabulary list.
const TCF_THEMES={
 A1:["个人信息","家庭与人物","日常生活","时间与数字","城市与地点","饮食与购物","交通与出行"],
 A2:["住房","工作","学习","健康","休闲与旅行","服务与行政","描述与感受"],
 B1:["工作与职业","教育与培训","健康与生活方式","住房与城市","旅行与交通","媒体与科技","环境","社会关系"],
 B2:["职场与就业","教育与机会","社会问题","环境与气候","科技与数字生活","媒体与信息","经济与消费","公共服务","观点与论证"],
 C1:["社会与公共政策","经济与全球化","科技与伦理","环境与转型","媒体与公共讨论","文化与身份","高级论证与连接"]
};
const TCF_RAW=[
["A1","个人信息","le nom","姓名"],["A1","个人信息","le prénom","名字"],["A1","个人信息","l’âge","年龄"],["A1","个人信息","l’adresse","地址"],["A1","个人信息","la nationalité","国籍"],["A1","个人信息","habiter","居住"],["A1","个人信息","être né","出生"],["A1","家庭与人物","la famille","家庭"],["A1","家庭与人物","les parents","父母"],["A1","家庭与人物","un enfant","孩子"],["A1","家庭与人物","un ami","朋友"],["A1","家庭与人物","gentil","友善的"],["A1","家庭与人物","jeune","年轻的"],["A1","家庭与人物","marié","已婚的"],["A1","日常生活","se lever","起床"],["A1","日常生活","travailler","工作"],["A1","日常生活","manger","吃"],["A1","日常生活","dormir","睡觉"],["A1","日常生活","commencer","开始"],["A1","日常生活","finir","结束"],["A1","日常生活","tous les jours","每天"],["A1","时间与数字","aujourd’hui","今天"],["A1","时间与数字","demain","明天"],["A1","时间与数字","hier","昨天"],["A1","时间与数字","le matin","早晨"],["A1","时间与数字","l’après-midi","下午"],["A1","时间与数字","le soir","晚上"],["A1","时间与数字","l’heure","时间；小时"],["A1","城市与地点","la ville","城市"],["A1","城市与地点","la rue","街道"],["A1","城市与地点","la gare","火车站"],["A1","城市与地点","la banque","银行"],["A1","城市与地点","la poste","邮局"],["A1","城市与地点","près de","靠近"],["A1","城市与地点","loin de","远离"],["A1","饮食与购物","acheter","购买"],["A1","饮食与购物","le prix","价格"],["A1","饮食与购物","payer","付款"],["A1","饮食与购物","le marché","市场"],["A1","饮食与购物","le repas","一餐"],["A1","饮食与购物","l’eau","水"],["A1","饮食与购物","le pain","面包"],["A1","交通与出行","le bus","公交车"],["A1","交通与出行","le train","火车"],["A1","交通与出行","le billet","票"],["A1","交通与出行","partir","出发"],["A1","交通与出行","arriver","到达"],["A1","交通与出行","à pied","步行"],["A1","交通与出行","en voiture","乘汽车"],

["A2","住房","le logement","住房"],["A2","住房","le loyer","房租"],["A2","住房","déménager","搬家"],["A2","住房","le voisin","邻居"],["A2","住房","meublé","带家具的"],["A2","住房","l’immeuble","楼房"],["A2","住房","l’étage","楼层"],["A2","工作","un emploi","工作；职位"],["A2","工作","un métier","职业"],["A2","工作","un collègue","同事"],["A2","工作","le salaire","工资"],["A2","工作","chercher un emploi","找工作"],["A2","工作","un entretien","面试；会谈"],["A2","工作","à temps plein","全职"],["A2","学习","les études","学业"],["A2","学习","un cours","课程"],["A2","学习","un examen","考试"],["A2","学习","réussir","成功；通过"],["A2","学习","apprendre","学习"],["A2","学习","s’inscrire","报名"],["A2","学习","une formation","培训"],["A2","健康","la santé","健康"],["A2","健康","un médecin","医生"],["A2","健康","un rendez-vous","预约"],["A2","健康","un médicament","药"],["A2","健康","avoir mal","疼"],["A2","健康","être malade","生病"],["A2","健康","se reposer","休息"],["A2","休闲与旅行","les vacances","假期"],["A2","休闲与旅行","voyager","旅行"],["A2","休闲与旅行","réserver","预订"],["A2","休闲与旅行","un hôtel","酒店"],["A2","休闲与旅行","visiter","参观"],["A2","休闲与旅行","un séjour","停留；旅居"],["A2","休闲与旅行","un loisir","休闲活动"],["A2","服务与行政","un document","文件"],["A2","服务与行政","un formulaire","表格"],["A2","服务与行政","remplir","填写"],["A2","服务与行政","un service","服务"],["A2","服务与行政","un permis","许可证"],["A2","服务与行政","une demande","申请；请求"],["A2","服务与行政","un compte bancaire","银行账户"],["A2","描述与感受","content","高兴的"],["A2","描述与感受","inquiet","担心的"],["A2","描述与感受","fatigué","疲惫的"],["A2","描述与感受","agréable","令人愉快的"],["A2","描述与感受","pratique","方便的；实用的"],["A2","描述与感受","difficile","困难的"],["A2","描述与感受","préférer","更喜欢"],

["B1","工作与职业","une entreprise","企业"],["B1","工作与职业","un contrat","合同"],["B1","工作与职业","une expérience professionnelle","工作经验"],["B1","工作与职业","postuler","申请职位"],["B1","工作与职业","être embauché","被录用"],["B1","工作与职业","une compétence","技能"],["B1","工作与职业","un poste","职位"],["B1","教育与培训","un diplôme","文凭"],["B1","教育与培训","une compétence linguistique","语言能力"],["B1","教育与培训","suivre une formation","参加培训"],["B1","教育与培训","progresser","进步"],["B1","教育与培训","une matière","学科"],["B1","教育与培训","obtenir un diplôme","获得文凭"],["B1","教育与培训","un apprentissage","学习；学徒制"],["B1","健康与生活方式","une alimentation équilibrée","均衡饮食"],["B1","健康与生活方式","faire de l’exercice","锻炼"],["B1","健康与生活方式","le stress","压力"],["B1","健康与生活方式","prévenir","预防"],["B1","健康与生活方式","un traitement","治疗"],["B1","健康与生活方式","améliorer sa santé","改善健康"],["B1","健康与生活方式","une habitude","习惯"],["B1","住房与城市","un quartier","街区"],["B1","住房与城市","les transports en commun","公共交通"],["B1","住房与城市","un espace public","公共空间"],["B1","住房与城市","le coût de la vie","生活成本"],["B1","住房与城市","un propriétaire","房东；业主"],["B1","住房与城市","un locataire","租客"],["B1","住房与城市","aménager","布置；改造"],["B1","旅行与交通","un déplacement","出行"],["B1","旅行与交通","un trajet","行程"],["B1","旅行与交通","un retard","延误"],["B1","旅行与交通","annuler","取消"],["B1","旅行与交通","une destination","目的地"],["B1","旅行与交通","un moyen de transport","交通方式"],["B1","旅行与交通","se déplacer","出行"],["B1","媒体与科技","les réseaux sociaux","社交网络"],["B1","媒体与科技","un appareil","设备"],["B1","媒体与科技","se connecter","连接；登录"],["B1","媒体与科技","partager","分享"],["B1","媒体与科技","une information","信息"],["B1","媒体与科技","un utilisateur","用户"],["B1","媒体与科技","en ligne","在线"],["B1","环境","l’environnement","环境"],["B1","环境","la pollution","污染"],["B1","环境","recycler","回收利用"],["B1","环境","économiser l’énergie","节约能源"],["B1","环境","les déchets","垃圾"],["B1","环境","protéger","保护"],["B1","环境","le climat","气候"],["B1","社会关系","une relation","关系"],["B1","社会关系","s’entendre avec","与……相处融洽"],["B1","社会关系","un désaccord","分歧"],["B1","社会关系","respecter","尊重"],["B1","社会关系","faire confiance à","信任"],["B1","社会关系","participer","参与"],["B1","社会关系","une association","协会"],

["B2","职场与就业","le recrutement","招聘"],["B2","职场与就业","le processus d’embauche","招聘流程"],["B2","职场与就业","une candidature","求职申请"],["B2","职场与就业","une qualification","资质"],["B2","职场与就业","évoluer professionnellement","职业发展"],["B2","职场与就业","concilier travail et vie privée","平衡工作与生活"],["B2","职场与就业","le marché du travail","劳动力市场"],["B2","教育与机会","l’égalité des chances","机会平等"],["B2","教育与机会","l’enseignement supérieur","高等教育"],["B2","教育与机会","acquérir des compétences","获得技能"],["B2","教育与机会","favoriser l’apprentissage","促进学习"],["B2","教育与机会","l’accès à l’éducation","教育机会"],["B2","教育与机会","une reconversion professionnelle","职业转型"],["B2","教育与机会","la formation continue","继续教育"],["B2","社会问题","les inégalités","不平等"],["B2","社会问题","l’exclusion sociale","社会排斥"],["B2","社会问题","la solidarité","社会互助"],["B2","社会问题","sensibiliser","提高意识"],["B2","社会问题","l’intégration","融入"],["B2","社会问题","une mesure sociale","社会措施"],["B2","社会问题","réduire un écart","缩小差距"],["B2","环境与气候","le changement climatique","气候变化"],["B2","环境与气候","les émissions","排放"],["B2","环境与气候","les énergies renouvelables","可再生能源"],["B2","环境与气候","réduire son empreinte carbone","减少碳足迹"],["B2","环境与气候","préserver les ressources","保护资源"],["B2","环境与气候","le développement durable","可持续发展"],["B2","环境与气候","une transition écologique","生态转型"],["B2","科技与数字生活","la protection des données","数据保护"],["B2","科技与数字生活","la vie privée","隐私"],["B2","科技与数字生活","une innovation","创新"],["B2","科技与数字生活","l’intelligence artificielle","人工智能"],["B2","科技与数字生活","la fracture numérique","数字鸿沟"],["B2","科技与数字生活","un usage responsable","负责任的使用"],["B2","科技与数字生活","automatiser","自动化"],["B2","媒体与信息","une source fiable","可靠来源"],["B2","媒体与信息","vérifier une information","核实信息"],["B2","媒体与信息","la désinformation","虚假信息"],["B2","媒体与信息","diffuser","传播"],["B2","媒体与信息","un point de vue","观点"],["B2","媒体与信息","influencer","影响"],["B2","媒体与信息","l’esprit critique","批判性思维"],["B2","经济与消费","le pouvoir d’achat","购买力"],["B2","经济与消费","une dépense","支出"],["B2","经济与消费","un budget","预算"],["B2","经济与消费","la hausse des prix","物价上涨"],["B2","经济与消费","consommer de manière responsable","负责任消费"],["B2","经济与消费","une aide financière","经济援助"],["B2","经济与消费","le niveau de vie","生活水平"],["B2","公共服务","une démarche administrative","行政手续"],["B2","公共服务","un service public","公共服务"],["B2","公共服务","un justificatif","证明材料"],["B2","公共服务","une demande de résidence","居留申请"],["B2","公共服务","être admissible","符合资格"],["B2","公共服务","un délai de traitement","处理期限"],["B2","公共服务","déposer un dossier","提交材料"],["B2","观点与论证","cependant","然而"],["B2","观点与论证","en revanche","相反；另一方面"],["B2","观点与论证","par conséquent","因此"],["B2","观点与论证","dans la mesure où","鉴于；在……程度上"],["B2","观点与论证","il convient de","应当"],["B2","观点与论证","mettre en évidence","突出；表明"],["B2","观点与论证","prendre en compte","考虑到"],

["C1","社会与公共政策","une politique publique","公共政策"],["C1","社会与公共政策","un enjeu de société","社会议题"],["C1","社会与公共政策","la cohésion sociale","社会凝聚力"],["C1","社会与公共政策","remédier à","补救；解决"],["C1","社会与公共政策","mettre en œuvre","实施"],["C1","社会与公共政策","une partie prenante","利益相关方"],["C1","社会与公共政策","un dispositif","机制；措施"],["C1","经济与全球化","la mondialisation","全球化"],["C1","经济与全球化","la croissance économique","经济增长"],["C1","经济与全球化","une pénurie","短缺"],["C1","经济与全球化","la main-d’œuvre","劳动力"],["C1","经济与全球化","un secteur en expansion","增长中的行业"],["C1","经济与全球化","accroître","增加"],["C1","经济与全球化","une retombée économique","经济效益"],["C1","科技与伦理","un biais algorithmique","算法偏差"],["C1","科技与伦理","la surveillance numérique","数字监控"],["C1","科技与伦理","un cadre réglementaire","监管框架"],["C1","科技与伦理","soulever une question","提出问题"],["C1","科技与伦理","porter atteinte à","损害"],["C1","科技与伦理","encadrer l’usage","规范使用"],["C1","科技与伦理","un progrès technologique","技术进步"],["C1","环境与转型","la biodiversité","生物多样性"],["C1","环境与转型","la sobriété énergétique","能源节制"],["C1","环境与转型","une ressource épuisable","可耗竭资源"],["C1","环境与转型","atténuer les effets","减轻影响"],["C1","环境与转型","une politique climatique","气候政策"],["C1","环境与转型","un modèle durable","可持续模式"],["C1","环境与转型","une transition énergétique","能源转型"],["C1","媒体与公共讨论","le traitement médiatique","媒体报道方式"],["C1","媒体与公共讨论","un débat public","公共讨论"],["C1","媒体与公共讨论","nuancer","使表达更有层次"],["C1","媒体与公共讨论","remettre en question","质疑"],["C1","媒体与公共讨论","une prise de position","立场表达"],["C1","媒体与公共讨论","un discours","论述；讲话"],["C1","媒体与公共讨论","un consensus","共识"],["C1","文化与身份","l’appartenance","归属"],["C1","文化与身份","la diversité culturelle","文化多样性"],["C1","文化与身份","une norme sociale","社会规范"],["C1","文化与身份","un patrimoine","文化遗产"],["C1","文化与身份","une identité collective","集体身份"],["C1","文化与身份","transmettre","传承；传递"],["C1","文化与身份","une représentation","表征；观念"],["C1","高级论证与连接","néanmoins","尽管如此"],["C1","高级论证与连接","en dépit de","尽管"],["C1","高级论证与连接","dans cette optique","从这一角度"],["C1","高级论证与连接","force est de constater que","不得不承认"],["C1","高级论证与连接","il n’en demeure pas moins que","尽管如此仍然"],["C1","高级论证与连接","à cet égard","在这方面"],["C1","高级论证与连接","dans une certaine mesure","在一定程度上"]
];
const TCF_VOCAB=TCF_RAW.map(([level,theme,f,z],i)=>({level,theme,f,z,id:"tcf-"+(i+1)}));
const TCF_GROUPS={};
for(const level of ["A1","A2","B1","B2","C1"]){
 const words=TCF_VOCAB.filter(x=>x.level===level);
 for(let i=0;i<words.length;i+=25){
   const n=i/25+1,key=level+"-"+n,chunk=words.slice(i,i+25);
   TCF_GROUPS[key]={level,group:n,count:chunk.length,themes:[...new Set(chunk.map(x=>x.theme))]};
 }
}
